### ISSUE TITLE
This u?

### ISSUE THREAD

**Issue by RandomVersion** [Mani175/Pirate-Cookie-Grabber#1]
i am nigga

**Comment by ArianFarrokhi** [comment]
mah dude XD

**Comment by RandomVersion** [comment]
And thats why Pyobf :tm: is the best python obfuscator.

**Comment by RandomVersion** [comment]
And not like this one used here

**Comment by RandomVersion** [comment]
You edited it

**Comment by RandomVersion** [comment]
[discord.com/api/webhooks/986252767934959667/O2sFFFA7TiQkuKkbp16o4k-vua08PXF0g9svgOw6JMUEaSsUj1JJDj3SJjFUELjrPjpn](https://discord.com/api/webhooks/986252767934959667/O2sFFFA7TiQkuKkbp16o4k-vua08PXF0g9svgOw6JMUEaSsUj1JJDj3SJjFUELjrPjpn)

**Comment by glosifyed** [comment]
> [discord.com/api/webhooks/986252767934959667/O2sFFFA7TiQkuKkbp16o4k-vua08PXF0g9svgOw6JMUEaSsUj1JJDj3SJjFUELjrPjpn](https://discord.com/api/webhooks/986252767934959667/O2sFFFA7TiQkuKkbp16o4k-vua08PXF0g9svgOw6JMUEaSsUj1JJDj3SJjFUELjrPjpn)

dw i got his new webhook and i deleted it lmfao
