### ISSUE TITLE
Many error codes?

### ISSUE THREAD

**Issue by Pasxeegamer** [Mani175/Pirate-Cookie-Grabber#22]
So, when i open it it shows that error?
![image](https://user-images.githubusercontent.com/80455968/190863683-05f7ca00-ce30-439a-a157-79607b2e8c06.png)

Ive installed all packages and other stuff and im **logged in** into edge and chrome with my
Roblox account?
How to fix

**Comment by Mani175** [comment]
bruh wtf u tryna use it in a zip pack? extract it my boy.

**Comment by Mani175** [comment]
jus unzip it

**Comment by Mani175** [comment]
oh wait what the fuck? you didn't set the webhook?
that's insane bruh, find `webhookk = "heh"` in the code and remove heh inside "" and paste your discord webhook in it
if you don't know what is that it's like sending messages through discord using scripts
if you don't know how to make one just search up youtube

**Comment by Pasxeegamer** [comment]
> oh wait what the fuck? you didn't set the webhook? that's insane bruh, find `webhookk = "heh"` in the code and remove heh inside "" and paste your discord webhook in it if you don't know what is that it's like sending messages through discord using scripts if you don't know how to make one just search up youtube

oh thank you i have done it
